"use client";

import { AlertTriangle, BrainCircuit, Info, Shield } from "lucide-react";
import { getIntelligenceSummary } from "@/lib/intelligence-data";

export default function IntelligenceView() {
  const summary = getIntelligenceSummary();

  const getSeverityBadge = (severity: string) => {
    switch (severity) {
      case "CRITICAL":
        return "bg-red-500/10 text-red-600 dark-soc:text-red-400 border-red-500/20";
      case "HIGH":
        return "bg-amber-500/10 text-amber-600 dark-soc:text-amber-400 border-amber-500/20";
      case "MEDIUM":
        return "bg-amber-500/10 text-amber-600 dark-soc:text-amber-400 border-amber-500/20";
      default:
        return "bg-emerald-500/10 text-emerald-600 dark-soc:text-emerald-400 border-emerald-500/20";
    }
  };

  return (
    <div className="mx-auto w-full max-w-7xl space-y-6 px-4 py-6 sm:px-6 lg:px-8">
      {/* Title Header */}
      <div>
        <div className="flex items-center gap-2 text-zinc-900 dark-soc:text-white">
          <BrainCircuit className="h-6 w-6 text-[#00E5FF]" />
          <h1 className="text-2xl font-bold tracking-tight">Intelligence</h1>
        </div>
        <p className="mt-1 text-sm text-zinc-500 dark-soc:text-zinc-400">
          AI-assisted risk assessment and anomaly analysis
        </p>
      </div>

      {/* Advisory Notice Banner */}
      <div className="rounded-xl border border-cyan-500/20 bg-cyan-50/50 p-4 dark-soc:border-cyan-500/30 dark-soc:bg-[#09223B]">
        <div className="flex items-start gap-3">
          <Info className="h-5 w-5 shrink-0 text-[#00E5FF] mt-0.5" />
          <div className="text-xs sm:text-sm text-zinc-700 dark-soc:text-zinc-300 leading-relaxed">
            <span className="font-semibold text-zinc-900 dark-soc:text-white">Note:</span> Assessments
            are generated by an AI-assisted analytical model. They highlight patterns that require
            analyst investigation. AI assessments are not definitive conclusions and should be
            validated against observed evidence.
          </div>
        </div>
      </div>

      {/* 4 Top KPI Cards */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {/* Risk Classification */}
        <div className="rounded-xl border border-zinc-200 bg-white p-5 shadow-sm dark-soc:border-[#1E2D56] dark-soc:bg-[#111C38]">
          <span className="text-xs font-semibold uppercase tracking-wider text-zinc-500 dark-soc:text-zinc-400">
            Risk Classification
          </span>
          <div className="mt-2 text-2xl font-bold text-amber-500">
            {summary.riskClassification}
          </div>
        </div>

        {/* Model Confidence */}
        <div className="rounded-xl border border-zinc-200 bg-white p-5 shadow-sm dark-soc:border-[#1E2D56] dark-soc:bg-[#111C38]">
          <span className="text-xs font-semibold uppercase tracking-wider text-zinc-500 dark-soc:text-zinc-400">
            Model Confidence
          </span>
          <div className="mt-2 text-2xl font-bold text-[#00E5FF]">
            {summary.modelConfidence}%
          </div>
        </div>

        {/* Anomalous Sessions */}
        <div className="rounded-xl border border-zinc-200 bg-white p-5 shadow-sm dark-soc:border-[#1E2D56] dark-soc:bg-[#111C38]">
          <span className="text-xs font-semibold uppercase tracking-wider text-zinc-500 dark-soc:text-zinc-400">
            Anomalous Sessions
          </span>
          <div className="mt-2 flex items-baseline gap-2">
            <span className="text-2xl font-bold text-amber-500">{summary.anomalousSessions}</span>
            <span className="text-xs text-zinc-500">out of {summary.totalSessions}</span>
          </div>
        </div>

        {/* Priority Items */}
        <div className="rounded-xl border border-zinc-200 bg-white p-5 shadow-sm dark-soc:border-[#1E2D56] dark-soc:bg-[#111C38]">
          <span className="text-xs font-semibold uppercase tracking-wider text-zinc-500 dark-soc:text-zinc-400">
            Priority Items
          </span>
          <div className="mt-2 flex items-baseline gap-2">
            <span className="text-2xl font-bold text-red-500">{summary.priorityItems}</span>
            <span className="text-xs text-zinc-500">requires attention</span>
          </div>
        </div>
      </div>

      {/* Assessment Cards List */}
      <div className="space-y-6">
        {summary.assessments.map((assessment, idx) => (
          <div
            key={assessment.id}
            className="rounded-xl border border-zinc-200 bg-white p-6 shadow-sm dark-soc:border-[#1E2D56] dark-soc:bg-[#111C38] space-y-5"
          >
            {/* Header */}
            <div className="flex flex-wrap items-start justify-between gap-3">
              <div className="flex items-start gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-zinc-100 text-zinc-800 dark-soc:bg-[#1E2D56] dark-soc:text-[#00E5FF] mt-0.5">
                  {idx === 0 ? (
                    <Shield className="h-5 w-5" aria-hidden="true" />
                  ) : (
                    <AlertTriangle className="h-5 w-5" aria-hidden="true" />
                  )}
                </div>
                <div>
                  <div className="flex items-center gap-2.5">
                    <h2 className="text-lg font-bold text-zinc-900 dark-soc:text-white">
                      {assessment.title}
                    </h2>
                    <span className="rounded-md border border-zinc-200 bg-zinc-50 px-2 py-0.5 text-xs font-medium text-zinc-600 dark-soc:border-[#1E2D56] dark-soc:bg-[#0D1735] dark-soc:text-zinc-300">
                      {assessment.badge}
                    </span>
                  </div>
                  <p className="text-xs text-zinc-400 mt-1">Generated {assessment.timestamp}</p>
                </div>
              </div>

              <span
                className={`rounded-md border px-3 py-1 text-xs font-bold uppercase tracking-wider ${getSeverityBadge(
                  assessment.severity,
                )}`}
              >
                {assessment.severity}
              </span>
            </div>

            {/* 3 Metric Columns */}
            <div className="grid grid-cols-1 gap-3 sm:grid-cols-3 rounded-lg border border-zinc-100 bg-zinc-50/70 p-4 dark-soc:border-[#1E2D56]/60 dark-soc:bg-[#0D1735]">
              <div>
                <span className="text-[11px] font-semibold uppercase tracking-wider text-zinc-400">
                  Risk Level
                </span>
                <div className="text-sm font-bold text-amber-500 mt-0.5">
                  {assessment.riskLevel}
                </div>
              </div>
              <div>
                <span className="text-[11px] font-semibold uppercase tracking-wider text-zinc-400">
                  Confidence
                </span>
                <div className="text-sm font-bold text-[#00E5FF] mt-0.5">
                  {assessment.confidence}%
                </div>
              </div>
              <div>
                <span className="text-[11px] font-semibold uppercase tracking-wider text-zinc-400">
                  Affected Sessions
                </span>
                <div className="text-sm font-bold text-zinc-900 dark-soc:text-white mt-0.5">
                  {assessment.affectedSessions}
                </div>
              </div>
            </div>

            {/* Assessment Paragraph */}
            <div>
              <span className="text-xs font-semibold uppercase tracking-wider text-zinc-500 dark-soc:text-zinc-400 block mb-1.5">
                Assessment
              </span>
              <p className="text-sm text-zinc-700 dark-soc:text-zinc-300 leading-relaxed">
                {assessment.assessment}
              </p>
            </div>

            {/* Contributing Factors */}
            <div>
              <span className="text-xs font-semibold uppercase tracking-wider text-zinc-500 dark-soc:text-zinc-400 block mb-2">
                Contributing Factors
              </span>
              <div className="space-y-2">
                {assessment.contributingFactors.map((factor, fIdx) => (
                  <div
                    key={fIdx}
                    className="flex items-center gap-2 rounded-lg border border-zinc-100 bg-zinc-50 px-3.5 py-2 text-xs sm:text-sm text-zinc-800 dark-soc:border-[#1E2D56]/60 dark-soc:bg-[#0D1735]/70 dark-soc:text-zinc-200"
                  >
                    <span className="h-1.5 w-1.5 rounded-full bg-amber-500 shrink-0" />
                    <span>{factor}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Recommendation Box */}
            <div className="rounded-xl border border-cyan-500/30 bg-cyan-50/40 p-4 dark-soc:border-cyan-500/30 dark-soc:bg-[#09223B]/60">
              <span className="text-xs font-bold uppercase tracking-wider text-cyan-700 dark-soc:text-[#00E5FF] block mb-1">
                Recommendation
              </span>
              <p className="text-xs sm:text-sm text-zinc-800 dark-soc:text-zinc-200">
                {assessment.recommendation}
              </p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
